# # # # # # # # #
# NEIGE CONFIG. #
# # # # # # # # #

# 1. Jekyll config
# 2. Site info
# 3. Navigation
# 4. Authors
# 5. Footer

# 1. Jekyll config
plugins:
  - jekyll-paginate
paginate: 6
paginate_path: "/page:num/"

# 2. Site info
title: 'Neige theme'
description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.'
baseUrl: 'https://neige-theme.com'
twitter: '@bellanger_q'

# 3. Navigation
navigation:
  - name: 'About'
    url: '/about'
    title: 'More about me'
    external: false
  - name: 'Contact'
    url: '/contact'
    title: 'Contact me'
    external: false
  - name: 'Twitter'
    url: 'https://twitter.com'
    title: 'Follow me on Twitter'
    external: true

# 4. Authors
authors:
  - id: "bilbo"
    name: "Bilbo Baggins"
    twitter: "@bilbo"
  - id: "jack"
    name: "Jack Sparrow"
    twitter: "@jack"

# 5. Footer
footer: <a href="https://neige-theme.com" target="_blank">Neige</a> theme by <a href="https://quentin-bellanger.com" target="_blank">Quentin</a> | Published with <a href="https://jekyllrb.com/" target="_blank">Jekyll</a>
