---
title: Neige
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
plugins:
- jekyll-paginate
highlighter: rouge
paginate: 4
paginate_path: "/page:num/"
icon: "/assets/img/icon.png"
favicon: "/assets/img/favicon.png"
og_image: "/assets/img/og.jpg"
lang: en
description: A minimalist and lightweight Jekyll blog theme
url: https://neige-theme.com
color: "#333333"
baseurl: 
css: "/assets/css/style.css"
twitter: "@bellanger_q"
navigation:
- name: About
  url: "/about"
  title: About Neige
  external: false
- name: Contact
  url: mailto:hello@quentin-bellanger.com
  title: Email me
  external: false
- name: Twitter
  url: https://twitter.com/bellanger_q
  title: Follow updates
  external: true
- name: GitHub
  url: https://github.com/bellangerq/neige-theme
  title: View source
  external: true
authors:
- id: quentin
  name: Quentin Bellanger
  twitter: "@bellanger_q"
footer: <a href="https://neige-theme.com" target="_blank" rel="noopener">Neige</a>
  theme by <a href="https://quentin-bellanger.com" target="_blank" rel="noopener">Quentin</a>
  | Published with <a href="https://jekyllrb.com/" target="_blank" rel="noopener">Jekyll</a>
